<?php echo $this->fetch('head.phtml'); ?>
<?php echo $this->fetch('header.phtml'); ?>
<?php echo $this->fetch('messages.phtml'); ?>

<h1></h1>
<div id="content">
    <div>
        <table id="blocks">
            <thead>
                <tr>
                    <th>LATEST BLOCKS</th>
                </tr>
                <tr>
                    <th class="col-md-4">Hash</th>
                    <th class="col-md-6">Value</th>
                </tr>
            </thead>
            <tbody id="blocks-body">

            </tbody>
        </table>
    </div>
    <hr>
    <div>
        <table id="transactions" class="table">
            <thead>
                <tr>
                    <th>LATEST TRANSACTIONS</th>
                </tr>
                <tr>
                    <th class="col-md-4">Hash</th>
                    <th class="col-md-6">Value</th>
                </tr>
            </thead>
            <tbody id="transactions-body">

            </tbody>
        </table>
    </div>
</div>

<script>
    var ws = new WS();
    ws.init();
</script>

<?php echo $this->fetch('footer.phtml'); ?>