<?php echo $this->fetch('head.phtml'); ?>
<?php echo $this->fetch('header.phtml'); ?>
<?php echo $this->fetch('messages.phtml'); ?>

<?php $blockInfo = $this->getAttribute('block_info'); ?>

<?php  $helper = $this->getAttribute('helper'); ?>
<h1>Block info</h1>
<div id="block-info">
    <?php if($blockInfo): ?>
        <table class="table">
            <thead>
            <tr>
                <th class="col-md-2">Key</th>
                <th class="col-md-6">Value</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Hash</td>
                    <td><?php echo $blockInfo->hash; ?></td>
                </tr>
                <tr>
                    <td>Version</td>
                    <td><?php echo $blockInfo->ver; ?></td>
                </tr>
                <tr>
                    <td>Previous block</td>
                    <td>
                        <a href="/transactions<?php echo $blockInfo->prev_block; ?>"><?php echo $blockInfo->prev_block; ?></a>
                    </td>
                </tr>
                <tr>
                    <td>Size</td>
                    <td><?php echo $blockInfo->size; ?></td>
                </tr>
                <tr>
                    <td>Height</td>
                    <td><?php echo $blockInfo->height; ?></td>
                </tr>
                <tr>
                    <td>Bits</td>
                    <td><?php echo $helper->toBtc($blockInfo->bits); ?></td>
                </tr>
                <tr>
                    <td>Fee</td>
                    <td><?php echo $helper->toBtc($blockInfo->fee); ?></td>
                </tr>
                <tr>
                    <td>Number of transactions</td>
                    <td><?php echo $blockInfo->n_tx; ?></td>
                </tr>
            </tbody>
        </table>
        <table class="table">
            <thead>
            <tr>
                <th>TRANSACTIONS LIST</th>
            </tr>
            <tr>
                <th class="col-md-2">Transaction</th>
                <th class="col-md-6">Amount</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach($blockInfo->tx as $tx): ?>
                    <tr>
                        <td>
                            <a href="/transaction/<?php echo $tx->hash; ?>"><?php echo $tx->hash; ?></a>
                        </td>
                        <td><?php echo $helper->toBtc($helper->getTransactionOutput($tx)); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <span>No info for this block.</span>
    <?php endif; ?>
</div>

<?php echo $this->fetch('footer.phtml'); ?>
