<?php echo $this->fetch('head.phtml'); ?>
<?php echo $this->fetch('header.phtml'); ?>
<?php echo $this->fetch('messages.phtml'); ?>

<h2>Check address balance</h2>
    <div>
        <form class="col-md-4">
            <div class="form-group">
                <label for="address">Address</label>
                <input id="address" type="text" class="form-control" id="address" placeholder="address hash...">
            </div>
            <button id="address_balance_btn" type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
    <div class="col-md-4">
        <span>Balance</span>
        <span id="balance" class="alert well-lg"></span>
    </div>

<script>
    jQuery('#address_balance_btn').click(function(event) {
        event.preventDefault();
        var address = jQuery('#address').val();
        if (address) {
            $.ajax({
                url: "/address/" + address,
                method: "GET"
            }).done(function(html) {
                $('#balance').html(parseInt(html) / 100000000 + " BTC");
            })
        }
    });

</script>

<?php echo $this->fetch('footer.phtml'); ?>